window.questions = [
  // Financial
  { id: 1, category: "Financial", text: "What is your ideal monthly budget for housing expenses, including taxes and insurance?" },
  { id: 2, category: "Financial", text: "Have you been pre-approved for a mortgage, and if so, for what amount?" },
  { id: 3, category: "Financial", text: "How much of a down payment are you comfortable making right now?" },
  { id: 4, category: "Financial", text: "Are you planning to sell a current property to fund this purchase?" },
  { id: 5, category: "Financial", text: "Do you have a specific lender you prefer to work with?" },
  { id: 6, category: "Financial", text: "What are your expectations regarding property taxes in your desired area?" },
  { id: 7, category: "Financial", text: "Are you interested in properties that might require renovation costs?" },
  { id: 8, category: "Financial", text: "How long do you plan to stay in this next home?" },
  { id: 9, category: "Financial", text: "Is this purchase purely residential or also an investment opportunity?" },
  { id: 10, category: "Financial", text: "Are there any HOA (Home Owners Association) fee limits you have in mind?" },
  { id: 11, category: "Financial", text: "Do you need to close by a specific date for tax purposes?" },
  { id: 12, category: "Financial", text: "How sensitive are you to interest rate fluctuations?" },
  { id: 13, category: "Financial", text: "Are you looking for a property with rental potential (e.g., basement suite)?" },
  { id: 14, category: "Financial", text: "What is your absolute maximum price point where you would walk away?" },
  { id: 15, category: "Financial", text: "Have you factored in closing costs (approx. 2-5% of purchase price)?" },

  // Family & Household
  { id: 16, category: "Family", text: "How many people will be living in the home full-time?" },
  { id: 17, category: "Family", text: "Do you have children, or do you plan to have children in the near future?" },
  { id: 18, category: "Family", text: "Do you have any pets? If so, what kind and how many?" },
  { id: 19, category: "Family", text: "Is a fenced yard a non-negotiable requirement for you?" },
  { id: 20, category: "Family", text: "Do you have elderly family members who may live with you or visit often?" },
  { id: 21, category: "Family", text: "How important is having a master bedroom on the main floor?" },
  { id: 22, category: "Family", text: "Do you need a dedicated playroom or recreational space for children?" },
  { id: 23, category: "Family", text: "Are specific school districts a priority for your search?" },
  { id: 24, category: "Family", text: "Do you need a guest room for frequent visitors?" },
  { id: 25, category: "Family", text: "How many bathrooms are essential for your household's morning routine?" },
  { id: 26, category: "Family", text: "Is a large dining area important for family gatherings?" },
  { id: 27, category: "Family", text: "Do you need a mudroom or drop-zone for kids' gear?" },
  { id: 28, category: "Family", text: "Are you looking for a multi-generational living setup?" },
  { id: 29, category: "Family", text: "How important is privacy from neighbors for your family?" },
  { id: 30, category: "Family", text: "Do you need a home office or study space for homework?" },

  // Work & Professional
  { id: 31, category: "Work", text: "Do you or your partner work from home remotely?" },
  { id: 32, category: "Work", text: "If you commute, what is the maximum commute time you are willing to tolerate?" },
  { id: 33, category: "Work", text: "Do you need high-speed fiber internet for your profession?" },
  { id: 34, category: "Work", text: "Do you need a dedicated office space with a door for video calls?" },
  { id: 35, category: "Work", text: "Is proximity to public transportation or highways critical for your job?" },
  { id: 36, category: "Work", text: "Do you require a workshop or garage space for your trade or hobbies?" },
  { id: 37, category: "Work", text: "Do you frequently host business clients at your home?" },
  { id: 38, category: "Work", text: "Are you likely to relocate for work in the next 3-5 years?" },
  { id: 39, category: "Work", text: "Do you need to be close to an airport for frequent travel?" },
  { id: 40, category: "Work", text: "Does your work require storage for inventory or equipment?" },
  { id: 41, category: "Work", text: "Do you work non-standard shifts where daytime noise might be an issue?" },
  { id: 42, category: "Work", text: "Is cell phone reception critical in the home (e.g., no dead zones)?" },
  { id: 43, category: "Work", text: "Do you need a separate entrance for a home business?" },
  { id: 44, category: "Work", text: "How important is the visual background for video conferencing?" },
  { id: 45, category: "Work", text: "Do you need to be near a specific city center for meetings?" },

  // Lifestyle & Entertainment
  { id: 46, category: "Lifestyle", text: "How often do you entertain guests or host parties?" },
  { id: 47, category: "Lifestyle", text: "Is an open-concept kitchen and living area important to you?" },
  { id: 48, category: "Lifestyle", text: "Do you enjoy gardening or outdoor landscaping work?" },
  { id: 49, category: "Lifestyle", text: "Is a swimming pool a desire, a deal-breaker, or a burden?" },
  { id: 50, category: "Lifestyle", text: "Do you need space for a home gym or workout equipment?" },
  { id: 51, category: "Lifestyle", text: "How important is walkability to coffee shops, restaurants, or parks?" },
  { id: 52, category: "Lifestyle", text: "Do you have any large hobbies (e.g., boating, RVing) that require parking?" },
  { id: 53, category: "Lifestyle", text: "Do you prefer a quiet, secluded neighborhood or a vibrant, active one?" },
  { id: 54, category: "Lifestyle", text: "Is an outdoor kitchen or BBQ area on your wishlist?" },
  { id: 55, category: "Lifestyle", text: "Do you need a media room or home theater setup?" },
  { id: 56, category: "Lifestyle", text: "Are you interested in smart home technology features?" },
  { id: 57, category: "Lifestyle", text: "How important is natural light and exposure (e.g., south-facing)?" },
  { id: 58, category: "Lifestyle", text: "Do you prefer modern, contemporary styles or traditional charm?" },
  { id: 59, category: "Lifestyle", text: "Is a fireplace a feature you would use and enjoy?" },
  { id: 60, category: "Lifestyle", text: "Do you need proximity to hiking trails, lakes, or nature?" },

  // Location & Commute
  { id: 61, category: "Location", text: "What is your preferred radius from your workplace?" },
  { id: 62, category: "Location", text: "Are there specific neighborhoods you absolutely want to avoid?" },
  { id: 63, category: "Location", text: "How important is being on a cul-de-sac or low-traffic street?" },
  { id: 64, category: "Location", text: "Do you prefer an urban, suburban, or rural setting?" },
  { id: 65, category: "Location", text: "Is proximity to a hospital or medical facilities important?" },
  { id: 66, category: "Location", text: "Do you rely on public transit for your daily commute?" },
  { id: 67, category: "Location", text: "How do you feel about corner lots?" },
  { id: 68, category: "Location", text: "Is the view (e.g., mountains, water, city) a major factor?" },
  { id: 69, category: "Location", text: "Are you concerned about future development in the area?" },
  { id: 70, category: "Location", text: "Do you want to be within walking distance of a grocery store?" },
  { id: 71, category: "Location", text: "How important is the crime rate or safety statistics of the area?" },
  { id: 72, category: "Location", text: "Do you need to be near a place of worship?" },
  { id: 73, category: "Location", text: "Are you okay with a property that backs onto a busy road?" },
  { id: 74, category: "Location", text: "Do you prefer a gated community?" },
  { id: 75, category: "Location", text: "How far are you willing to drive for basic amenities?" },

  // Property Specifics
  { id: 76, category: "Property", text: "What is your minimum and maximum square footage requirement?" },
  { id: 77, category: "Property", text: "Do you prefer a single-story (ranch) or two-story home?" },
  { id: 78, category: "Property", text: "Is a basement required, and if so, does it need to be finished?" },
  { id: 79, category: "Property", text: "What type of parking do you need (e.g., 2-car garage, street parking)?" },
  { id: 80, category: "Property", text: "Do you have a preference for heating/cooling systems (e.g., central air)?" },
  { id: 81, category: "Property", text: "Are you open to condos or townhomes, or only single-family homes?" },
  { id: 82, category: "Property", text: "How important is the age of the home to you?" },
  { id: 83, category: "Property", text: "Do you prefer a large lot with maintenance or a small, low-maintenance lot?" },
  { id: 84, category: "Property", text: "Is hardwood flooring a must-have?" },
  { id: 85, category: "Property", text: "Do you need a laundry room on a specific floor?" },
  { id: 86, category: "Property", text: "Are you looking for energy-efficient features (solar, tankless heater)?" },
  { id: 87, category: "Property", text: "Do you need wheelchair accessibility features now or later?" },
  { id: 88, category: "Property", text: "Is the exterior material important (brick, siding, stucco)?" },
  { id: 89, category: "Property", text: "Do you need a lot of closet and storage space?" },
  { id: 90, category: "Property", text: "Are you okay with a shared driveway?" },

  // Future & Miscellaneous
  { id: 91, category: "Future", text: "Where do you see yourself living in 10 years?" },
  { id: 92, category: "Future", text: "Are you buying this home with resale value as a primary concern?" },
  { id: 93, category: "Future", text: "Do you plan to rent this property out eventually?" },
  { id: 94, category: "Future", text: "Are you expecting any major life changes (marriage, retirement) soon?" },
  { id: 95, category: "Future", text: "How handy are you with home repairs?" },
  { id: 96, category: "Future", text: "What is the one thing you hated most about your last home?" },
  { id: 97, category: "Future", text: "What is the one thing you loved most about your last home?" },
  { id: 98, category: "Future", text: "If you could only have one 'luxury' feature, what would it be?" },
  { id: 99, category: "Future", text: "How quickly do you need to move in?" },
  { id: 100, category: "Future", text: "Are there any deal-breakers we haven't discussed yet?" },

  // Entertainment
  { id: 101, category: "Entertainment", text: "When you entertain, is it usually formal dinner parties or casual get-togethers?" },
  { id: 102, category: "Entertainment", text: "Do you need a layout that allows for separation between adult and child entertainment areas?" },
  { id: 103, category: "Entertainment", text: "Is the acoustic quality of a room important to you for music or movies?" },
  { id: 104, category: "Entertainment", text: "Do you envision hosting outdoor events that would require extensive parking availability?" },
  { id: 105, category: "Entertainment", text: "How important is it to have a 'wow' factor feature (like a grand entrance or view) for impressing guests?" },
  { id: 106, category: "Entertainment", text: "Do you need specific electrical or structural support for heavy entertainment equipment (e.g., pool table, grand piano)?" },
  { id: 107, category: "Entertainment", text: "Is proximity to major sports stadiums or arenas a pro or a con for you?" },
  { id: 108, category: "Entertainment", text: "Do you require a wet bar or butler's pantry to facilitate serving drinks and food?" },
  { id: 109, category: "Entertainment", text: "How do you feel about smart lighting systems designed for creating ambiance?" },
  { id: 110, category: "Entertainment", text: "Is privacy from neighbors a major concern when you are entertaining outdoors?" },
];
